apiVersion: v1
kind: Secret
metadata:
  name: citizen-db-secret
  namespace: citizens
type: Opaque
stringData:
  # MySQL password for root user
  mysql-root-password: ff41ghfghgfhgWM2sgTYfdfsdfZ= 
  # Non-root user password
  mysql-password: dsd4xM6dfgKfsdf9dfsJ    